### ISSUE TITLE
Typo in https://docs.anychart.com/Stock_Charts/Price_Indicator

### ISSUE THREAD

**Issue by RubberArchind** [AnyChart/docs.anychart.com#6]
![image](https://user-images.githubusercontent.com/35050952/105503238-eba47300-5cf8-11eb-980c-cb2e67517814.png)

i found a typo there there are no close curly bracket for the first line

**Comment by Shestac92** [comment]
@RubberArchind 
Thank you for the report! We will correct the typo in the documentation.
